### ISSUE TITLE
some other latexed jaynes material

### ISSUE THREAD

**Issue by andrewfowlie** [lawrennd/jaynes#2]
https://andrewfowlie.github.io/resource/jaynes/

I think I started with those ones because the only versions I had were so terrible quality. I had a plan to OCR more of them, but it was surprisingly hard work. You are welcome to add those to your collection here!

**Comment by lawrennd** [comment]
It is a real labour of love! I ended up using Mathpix snip, but a lot of hand editing too.

I'll make sure a link to your page is added to the README.md!
